### ISSUE TITLE
Switch video in current page

### ISSUE THREAD

**Issue by RexSkz** [DIYgod/DPlayer#20]
Hello,

Recently I started to write a video page using DPlayer for my small team, and here is my need:

There're some buttons in a page, and when I press one of them, the video that DPlayer shows can be changed, without reloading page or something else.

But I noted that DPlayer can only be initialized once using `new DPlayer({...})`, and the settings can't be changed any longer. I tried using `new DPlayer` each time when button was pressed, but it made too much events attached to `document`. So when I press 'Space' key after changing a video, new video paused, and old video played.

I think it's useful to add a method like `loadVideo` so that DPlayer can be used in any single page application.

By the way, DPlayer is the best danmaku player I've ever seen. Thank you for sharing such an awesome project.

Best regards!

**Comment by Myer921** [comment]
Diygod又要修修修了，然后我就要找豆子一起爆炸了
BOOM！

**Comment by dixyes** [comment]
这是一个特性 不是bug 蛤蛤蛤
你自己爆炸 我还有坑(pigu)要填(wan)

It's not a bug but a feature looooool (joke
This issue occurs in aplayer too: left ,right and space keys will act on all dplayer and aplayer in this page, this will cause duoshuo (a Chinese comment system like discus) can not type space or move cursor by arrow keys (not tested with discus, maybe the same
It seems that I have to update hexo-tag-dplayer for such a change(if this fix will remove init function), however I'm wasting my life on playing Overwatch, can't stop
Sorry for my dumb English,i hope DlYGod can understand this

**Comment by RexSkz** [comment]
@dixyes 

If there're more than one video in a page, I think the way to solve your problem is to disable keyboard shortcuts, or add event listeners for each `video` but not `document`. The former one is better.

如果一个页面有很多视频，那么我觉得最好的方式就是禁用快捷键，或者只为每个 `video` 绑定而不是为整个 `document`。感觉前者更好一些。

话说原来这里可以发中文啊，之前在某个项目里面发中文被鄙视了……

**Comment by dixyes** [comment]
I think video can be played at the same time in same page, but audio should have a focus, only one audio plays in one page, the key controll this one. When focus is in input area, key binding should be disabled, so that you can input space in input areas.
我觉得一个页面视频很多还可以，但是音频要有个焦点，只有一个音频在一个页面上播放，键盘控制焦点音频。当页面输入文本时，解除键盘绑定，这样就可以输入空格了。
For now, just add a option for keyboard control like"kbcon:False", or a api like togglekbcontrol() function
现在的话，加一个选项“键盘控制”或者一个函数“togglekbcontrol()”这样就可以解决问题了
For change video isssue only, if it's hard to make "loadVideo" function, maybe "destory" is easier(
如果只考虑更换视频的问题的话，loadVideo很麻烦的话，添个destory就好了（
not professional opinion, for reference only
以上是并不会js和前端的我的非专业意见，仅供参考

我觉得蛤 一句话没有啥建设性意义，只是卖个萌的话，只用中文写出来没啥不对的，好意见就用双语有利于分享（所以我这种渣英语的就经常写汉语

**Comment by DIYgod** [comment]
Done. https://github.com/DIYgod/DPlayer/commit/a70b1229aba7e32aaf911a074f2689f1020bbad7

An option added: hotkey.
