### ISSUE TITLE
在这里提几个小需求...

### ISSUE THREAD

**Issue by yebukong** [DIYgod/DPlayer#50]
1.  希望增加一个控制是否可以发送弹幕的方法或参数
> 比如当设置无法发送弹幕时，弹幕提交框会隐藏,变灰或者弹出提示等
2. 希望增加一个控制弹幕滑动速度的参数
> 现在在视频界面很小时弹幕滑动会加快，甚至会很晃眼，以至于无法看清弹幕 
3. 希望可以设置author属性
> 我注意到提交的弹幕json中有一个author属性，此属性无法设置，只能是"DIYgod",希望可以开放设置
>此属性可以用来存放用户id等信息
4. 希望可以在播放器构造方法中添加更多可选属性
> 在现有设置按钮下的弹幕开关，弹幕透明度，播放速度等属性都可以加入到DPlayer的作为初始化参数
5. 希望增加对播放器中的json属性的更多介绍
>比如弹幕的参数player为什么是数组格式？

**Comment by liwanglin12** [comment]
@yebukong “会议的最后我再多说两句”

**Comment by DIYgod** [comment]
1 3, you should realize it yourself, I can not integrate a user system into a simple palyer.

5, it's my mistake, but the old data is inconvenience to modify.

**Comment by liwanglin12** [comment]
@DIYgod I think point 3 should be you case

**Comment by DIYgod** [comment]
@liwanglin12 OK, I will add a new opiton, and the default user name is user id.

**Comment by yebukong** [comment]
@DIYgod  Thank you for your response，For 1 and 3 I will realize through myself
- ps : My English is so poor,so I use the baidu translation

**Comment by liwanglin12** [comment]
@yebukong I suggest you use bing / netease or Google Translation.
One more, Chinglish is ok.

**Comment by Myer921** [comment]
............................ 都是中国人
你们真......够了

**Comment by ShanaMaid** [comment]
@Myer921 But users are not all chinese!

**Comment by Myer921** [comment]
@ShanaMaid 
确实，但是你看看楼上
我选择 GG
----------------------
Google Translate
Yes, but you look upstairs
I chose GG

**Comment by mike-hor** [comment]
sure,have nothing to say

**Comment by znfighting** [comment]
I really hope you can add an option to allow users to change the speed of barrage. Because the speed is too fast when we put it on a big scrren,not a computer,is a big screen..I have noticed that you have a classname called 'dplayer-danmaku-move' to control  the animation duration time, which is connected to the speed of barrage,but that time is a number which has been setted in the css file. It won‘t work when we want to change the time or speed according to user's own will.
